### ISSUE TITLE
请问mediacodec的兼容性怎么处理的?

### ISSUE THREAD

**Issue by foobra** [lmylr/hwvc#1]
感觉比较麻烦 , 难道只能每个手机测试后开白名单吗?

**Comment by imalimin** [comment]
目前MediaCodec的主要问题在于是否支持high跟main，这里可以采取先判断后重试的策略，这个在大多机型上都没什么问题。别的问题也可可以采取同样的策略，比如ABR/CBR、pts等问题。
1. 先根据系统版本判断是否支持这个特性，比如high/main。
2. 支持则以high/main模式启动MediaCodec。
3. 如果失败，则直接使用baseline重启MediaCodec

**Comment by foobra** [comment]
@lmylr high main这个是需要每个手机测试的吧? 直接api查询应该查询不到吧?

**Comment by imalimin** [comment]
看Android源码可以知道Android 7及以上才支持high/main

**Comment by foobra** [comment]
好的 感谢 我去看下
